### ISSUE TITLE
Digital Ocean Kubernetes Cluster Not creating. Giving Error : The argument "size" is required, but no definition was found.

### ISSUE THREAD

**Issue by Jahadul-Rakib** [cdktf/cdktf-provider-digitalocean#10]
Hello sir,
I am going to create a kubernetes cluster using cdktf and cdktf-provider-digitalocean...but i am stucking in a place .... i can not understand how can i overcome this issue. please help me....

### cdktf & Language Versions

Java and library cdktf-provider-digitalocean(0.0.6 to 0.0.0)

### Expected Behavior

**create kubernetes cluster**

### Actual Behavior
_Error: Missing required argument_
_The argument "size" is required, but no definition was found._

### Steps to Reproduce

```
        KubernetesCluster kubernetesCluster = KubernetesCluster.Builder.create (this, dto.getClusterName ())
                .name (dto.getClusterName ())
                .vpcUuid (vpc.getId ())
                .version (dto.getK8sVersion ())
                .region (dto.getRegion ())
                .autoUpgrade (true)
                .surgeUpgrade (true)
                .ha (dto.getHighAvailability ())
                .nodePool (KubernetesClusterNodePool.builder ()
                        .name ("default-node-group")
                        .nodeCount (dto.getDefaultNodeTotal ())
                        .size (dto.getDefaultNodeType ())
                        .build ())
                .dependsOn (List.of (vpc))
                .build ();
```

**Comment by DanielMSchmidt** [comment]
Could you try hardcoding a value in the `.size()` call, e.g. `.size("s-2vcpu-2gb")`? The error reads to me like it misses the size attribute on the node pool.

**Comment by Jahadul-Rakib** [comment]
yes.. i also try hard coded value....i solve this issues manually adding size attribute but from library its do not work properly.

**Comment by DanielMSchmidt** [comment]
What do you mean with manually adding the size attribute?

**Comment by Jahadul-Rakib** [comment]
Yes sir @DanielMSchmidt
